SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX PG_PARAM_OBJECT_IDX_001 ON PARAMETER_OBJECT;



/* Drop Tables */

DROP TABLE IF EXISTS PARAMETER_AUDIT;
DROP TABLE IF EXISTS PARAMETER_OBJECT;
DROP TABLE IF EXISTS PARAMETER_SEQENCE;




/* Create Tables */

-- 参数修改日志
CREATE TABLE PARAMETER_AUDIT
(
	PARAM_AUDIT_SEQ INT NOT NULL AUTO_INCREMENT COMMENT 'PARAM_AUDIT_SEQ',
	ORG_ID VARCHAR(12) COMMENT '机构Id',
	EFFECTIVE_DATE TIMESTAMP DEFAULT NOW() COMMENT '生效日期',
	PARAM_KEY VARCHAR(100) NOT NULL COMMENT '参数主键',
	PARAM_CLASS VARCHAR(100) NOT NULL COMMENT '参数类别',
	-- ///
	-- INSERT|插入
	-- UPDATE|更新
	-- DELETE|删除
	PARAM_OPERATION VARCHAR(10) NOT NULL COMMENT '操作',
	NEW_OBJECT MEDIUMTEXT COMMENT '新参数值',
	OLD_OBJECT MEDIUMTEXT COMMENT '原参数值',
	UPDATE_LOG MEDIUMTEXT COMMENT '修改日志',
	MTN_USER VARCHAR(40) COMMENT '修改用户',
	MTN_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL COMMENT '修改时间',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (PARAM_AUDIT_SEQ)
) COMMENT = '参数修改日志';


-- 参数对象表
CREATE TABLE PARAMETER_OBJECT
(
	ORG_ID VARCHAR(12) NOT NULL COMMENT '机构Id',
	PARAM_CLASS VARCHAR(100) NOT NULL COMMENT '参数类别',
	PARAM_KEY VARCHAR(100) NOT NULL COMMENT '参数主键',
	EFFECTIVE_DATE TIMESTAMP DEFAULT NOW() NOT NULL COMMENT '生效日期',
	PARAM_OBJECT MEDIUMTEXT COMMENT '参数内容',
	MTN_TIMESTAMP TIMESTAMP DEFAULT NOW() COMMENT '修改时间',
	MTN_USER VARCHAR(40) COMMENT '修改用户',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ORG_ID, PARAM_CLASS, PARAM_KEY, EFFECTIVE_DATE)
) COMMENT = '参数对象表';


-- 参数序列生成表
CREATE TABLE PARAMETER_SEQENCE
(
	PARAM_NAME VARCHAR(50) NOT NULL COMMENT '参数名称',
	PARAM_SEQ INT DEFAULT 0 NOT NULL COMMENT '参数ID序列',
	BIZ_DATE DATE NOT NULL COMMENT '业务日期',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (PARAM_NAME)
) COMMENT = '参数序列生成表';



/* Create Indexes */

CREATE INDEX PG_PARAM_OBJECT_IDX_001 ON PARAMETER_OBJECT (PARAM_CLASS ASC);



